name: Deploy

on:
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Alterações realizadas'
        required: true
        default: 'Desc'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install sshpass
      - name: Delete old files
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST "
            rm -rf /var/www/clinipet/*
          "
      - name: Deploy to server
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/var/www/clinipet
      - name: Set Environment Variables
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST "
           mv /var/www/clinipet/assets/js/config.model.js /var/www/clinipet/assets/js/config.js &&
           sed -i 's|%%API_URL%%|https://clinipet.sytes.net|g' /var/www/clinipet/assets/js/config.js &&
           sed -i 's|%%BASE_URL%%|https://clinipet.sytes.net|g' /var/www/clinipet/assets/js/config.js &&
           echo 'Frontend configurado.'
          "
          
