name: Deploy

on:
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Alterações realizadas'
        required: true
        default: 'Desc'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to server
        run: |
          scp -r . ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/var/www/clinipet

      - name: Print deployment message
        run: echo "Alteracoes: ${{ github.event.inputs.deploy_message }}"
